# The main config file for your Jekyll template

# Site settings
title: Ricky Moorhouse               # used for the html title of every page
desc: Random thoughts and ramblings

url: http://rickymoorhouse.co.uk/      # put your website hosting url here
baseurl: ''                 # the subpath of your site, e.g. /blog
permalink: /:year/:month/:day/:title/   # how should we display posts url

# Meta settings
email: hi@rickymoorhouse.co.uk
author: Ricky Moorhouse
twitter_username: rickymoorhouse
github_username: rickymoorhouse
github_source: rickymoorhouse.github.io

# Put your ga tracking code below
google_analytics: 'UA-XXXXXXXX-X'

mapbox_id: 'outdoors-v10'
# Mapbox settings
mapbox_token: 'pk.eyJ1Ijoicmlja3ltb29yaG91c2UiLCJhIjoiY2lnemh4eGF1MHc0NDRwbTNteW9sN2p0NyJ9.P_XKTG1fyN2jP_R_G1JMdQ'

# Pagination settings
paginate: 5                           # number of posts to show per page
paginate_path: "/blog/page:num/"  # link scheme for articles, should be letf as is

# Navigation settings
# Used to define the navigation menu items
# > Title is the tile of the navigation item, url the url and desc is the tooltip
navigation:
  - title: Blog
    url: /blog/
    desc: Stuffs I write about
  - title: Projects
    url: /projects/
    desc: Stuffs I like to do
  - title: "Places I've visited"
    url: /travel/
    desc: My map of places I have visited

# Used by Jekyll to recognize what is a post and what is a page
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post

collections:
  travel: 
    output: true


# Markdown parser settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false          # you can change this if you feel like it
  parse_block_html: true    # allow parsing html inside markdown

# Build settings
include:
  - _pages                  # all your pages can be put inside pages (except articles)
exclude:
  - README.md
  - vendor
plugins:
  - jekyll-paginate
